collections:
  tags:
    output: true
    permalink: /tags/:name/

title: Teiki
email: rafaeleikimi@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Por Rafael Eiki
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
github_username:  rafaeleiki

# Build settings
markdown: kramdown
theme: jekyll-theme-cayman
gems:
  - jekyll-feed
  - octopress-debugger
exclude:
  - Gemfile
  - Gemfile.lock
  - run.sh
